[카드게임 미션 - 1단계] 곽가영 미션 제출합니다.
LIN-KHU/javascript-cardgame pull request #5
Opened 2024-01-07 02:23 UTC by gykwak03

안녕하세요.

처음에 npm쓸 줄도 모르고 css 적용이 안 되어서 어려움을 겪었었는데 
웹팩 적용과 class 사용하여 button 객체 만드는 부분에서 멘토님들께서 도움을 주셔서 잘 해결했습니다.

감사합니다.

2024-01-07 13:45 UTC, tkdrb12 requested changes
안녕하세요 가영님! 

몇가지 코멘트 드리자면 
1. commit을 할때 구현한 기능 단위로 commit을 해보는 걸 추천드립니다!
2. 시간이 되신다면 `prettier`를 사용해보시는 걸 추천드릴게요 코드 포맷팅 기능이 아주 편리하답니다

2024-01-07 13:45 UTC, tkdrb12 commented on src/index.js
> +const card3 = new Card('id3');
해당 카드 객체의 id 값을 가지고 있는 것은 좋지만 id값이 지금 당장 사용되지 않고 있어요 사용하지 않는 코드는 제거하는 게 좋습니다😀

2024-01-07 13:45 UTC, tkdrb12 commented on src/index.js
> +const win = Math.floor(Math.random() * 3);
0~2 범위의 정수를 랜덤으로 생성해주는 기능이군요!
하지만 `win` 해당 변수의 이름으로 적절하지 않아보여요 좀 더 적절한 이름을 지어보는 건 어떨까요?

2024-01-07 13:45 UTC, tkdrb12 commented on src/index.js
> +    if(win == i){
`==` 연산자와 `===` 연산자의 차이는 무엇일까요?

2024-01-07 13:45 UTC, tkdrb12 commented on src/index.js
> +      document.write('정답입니다')
`cards`요소의 child로 추가해보는 건 어떨까요?

2024-01-07 13:45 UTC, tkdrb12 commented on src/index.js
> +for (let i = 0; i<3; i++){
for문은 휴먼 에러를 일으키기 쉬워 `forEach`, `map` 와 같은 배열 메소드를 사용하는 걸 추천드립니다!

2024-01-07 13:45 UTC, tkdrb12 commented on src/index.js
> +}
파일의 마지막은 한칸 띄워주는 게 (EOL) 컨벤션입니다!

2024-01-07 13:45 UTC, tkdrb12 commented on src/index.js
> +class Card {
class 클래스를 다른 파일로 분리시켜 볼까요?

2024-01-07 16:45 UTC, gykwak03 commented on src/index.js
> +const card3 = new Card('id3');
넵 수정하겠습니다!!

2024-01-07 17:13 UTC, gykwak03 commented on src/index.js
> +const win = Math.floor(Math.random() * 3);
당첨되다의 의미인 win을 사용하여 표현했는데 의미 전달이 잘 안되었군요 수정하겠습니다!!
변수명을 수정하고자 멘토분들이 쓴 코드를 참조하려 했는데 혹시 어디에 저장하셨는지 알려주실 수 있을까요?

2024-01-07 17:15 UTC, gykwak03 commented on src/index.js
> +    if(win == i){
== 는 단순히 값이 같은지만을 물어보는 연산자입니다. 
"1" == 1 이면 True가 됩니다.

===는 엄격한 연산자로, 데이터 타입까지 같아야 True가 됩니다. 
"1" === 1 이면 False가 됩니다.

2024-01-07 17:22 UTC, gykwak03 commented on src/index.js
> +      document.write('정답입니다')
cardsContainer.appendChild(card1.card);
cardsContainer.appendChild(card2.card);
cardsContainer.appendChild(card3.card); 
이렇게 추가하시라는 말씀이신걸까요?

2024-01-07 17:29 UTC, gykwak03 commented on src/index.js
> +for (let i = 0; i<3; i++){
넵 forEach 사용해보겠습니다!

2024-01-07 17:30 UTC, gykwak03 commented on src/index.js
> +}
기억하겠습니다!

2024-01-07 17:49 UTC, gykwak03 commented on src/index.js
> +class Card {
분리해보려고 하였으나 Card 클래스가 index.js에서 제대로 잘 임포트 되지 않는 것 같습니다.. 카드가 생성이 안됩니다 ㅠㅠ 

일단 고치지 않은 작동 되는 코드하고 
나름대로 고쳐본  작동되지 않는 코드 두개 push해도 괜찮을까요?

2024-01-07 18:09 UTC, gykwak03 commented
> 2\. 사용해보시는 걸 추천드릴게요 코드 포맷팅 기능이 아주 편리하답니다~

commit을 할때 구현한 기능 단위로 commit을 해보는 걸 추천드립니다! 
-> 넵 알겠습니다!! 이번에 수정하면서 깜빡했는데 .. 다음번엔 조언하신 것 단위로 commit하겠습니다. 

시간이 되신다면 prettier를 사용해보시는 걸 추천드릴게요 코드 포맷팅 기능이 아주 편리하답니다~
-> 이거 방금 깔아서 써봤는데 컨벤션 부분 많이 잡아주네요 추천 감사합니다!!

추가로 테스트는 잘 통과가 되는데 혹시 어디에서 문제가 발생했을까요?
->이거 터미널 한개에다가 npm run test만 실행해서 fail로 떴었습니다. 
터미널 한개에다간 start 하고 다른 한개에다간 test 하니까 잘 통과가 되었습니다!!

2024-01-08 14:24 UTC, tkdrb12 commented on src/index.js
> +      document.write('정답입니다')
아니요 이 코드 `document.write('정답입니다')`를 수정해보면 어떨까 제안드린거에요!

2024-01-08 14:33 UTC, tkdrb12 commented on src/index.js
> +class Card {
모듈은 성공적으로 나누어졌습니다!
오류가 발생한 원인은 따로 있는데요 콘솔창을 확인해보면 `cardsContainer is not defined` 이라는 오류메세지가 발생하는 것을 확인할 수 있습니다.
그렇다면 오류가 발생한 원인은 무엇일까요?

또한 모듈에 대해서 공부해보면 좋을 것 같아 두가지 질문을 드립니다.
1. 모듈을 나눌 때 사용하는 방법은 import외에도 require을 사용할 수 있습니다. 둘의 차이점은 무엇일까요?
2. export를 하는 방법은 export default 와 export가 있습니다. 차이점은 무엇일까요?

2024-01-08 16:42 UTC, tkdrb12 commented on src/index.js
> +const win = Math.floor(Math.random() * 3);
merge된 PR을 참조하시면 됩니다! pull request에서 closed 탭을 찾아보면 있을거에요

2024-01-08 20:49 UTC, gykwak03 commented on src/index.js
> +      document.write('정답입니다')
아 이해했습니다!!

2024-01-08 21:03 UTC, gykwak03 commented on src/index.js
> +class Card {
cardsContainer를 생성자 변수로 넣으니까 해결되었습니다!!
1. import는 ECMAScript에서만 사용할 수 있고 파일의 시작지점에서만 사용할 수 있습니다. 그러나 require는 CommonJS를 사용하며 어느 지점에서나 사용할 수 있습니다. 
2. export default는 해당 모듈엔 하나의 개체가 있다는 것으로 받아들여져서 해당 모듈의 전체 개체를 export 하는 의미를 갖습니다. 반면에 export는 여러개의 개체가 있는 라이브러리 형태의 모듈에서 가져오기 할 때 사용되기에 특정 개체만 가져오는 것이 가능합니다.

2024-01-09 04:22 UTC, tkdrb12 approved these changes
남겨주신 코멘트 확인했습니다.
고생많으셨어요~

2024-01-09 04:22 UTC, merged