[카드 뒤집기 미션-1단계] 이수진 미션 제출합니다.
LIN-KHU/javascript-cardgame pull request #6
Opened 2024-01-07 05:51 UTC by sujin0707

2024-01-07 14:57 UTC, tkdrb12 requested changes
안녕하세요 수진님!

올려주신 코드 잘 확인했습니다.
전반적으로 가독성이 좋은 코드였습니다!
변수명이나 함수명을 잘 지어 주신것도 좋았습니다👍

하지만 commit할 때는 기능 단위로 commit을 하는 것을 추천드립니다!
구현할 기능을 한번에 commit하다보면 나중에 협업을 할때 불편한 부분이 분명 생길거에요 🥲

첫 미션 고생하셨고 코멘트에 답변 부탁드리겠습니다!

2024-01-07 14:57 UTC, tkdrb12 commented on index.css
> +  font-size: 16px;
font-size도 설정해주시다니 세세하시네요👍

2024-01-07 14:57 UTC, tkdrb12 commented on package.json
> +    "jest": "^29.7.0",
jest는 어떤 이유로 추가해주셨는지 알 수 있을까요?
jest와 cypress의 차이는 무엇일까요?

2024-01-07 14:57 UTC, tkdrb12 commented on src/Card.js
> +  }g
여기 오타 수정부탁드릴게요~

2024-01-07 14:57 UTC, tkdrb12 commented on src/index.js
> +class CardGame {
CardGame class도 별도의 파일로 분리해보는건 어떨까요?

2024-01-07 14:57 UTC, tkdrb12 commented on src/Card.js
> +    this.element.addEventListener('click', this.handleCardClick.bind(this));
1. 바인딩을 사용해주셨는데 바인딩이란 무엇일까요?
2. 이벤트 핸들러를 이벤트에 연결할 때  바인딩을 사용하는 이유는 무엇일까요?
3. bind 함수는 Function.prototype의 메소드를 사용한 명시적 바인딩입니다. 다른 바인딩 방법으로는 뭐가 있을까요?

2024-01-07 14:57 UTC, tkdrb12 commented on src/Card.js
> +    alert(this.isWinner ? '당첨입니다' : '꽝입니다');
이번에는 alert창을 띄우는게 아닌 document내에 텍스트를 삽입하도록 코드를 수정해보죠!

2024-01-07 14:57 UTC, tkdrb12 commented on src/index.js
> +cardGame.start();
파일의 마지막은 한칸 띄워주시는 게 컨벤션(EOL) 입니다!

2024-01-07 14:57 UTC, tkdrb12 commented on src/index.js
> +cardGame.start();
현재 cardGame객체에는 start메소드가 존재하지 않습니다.
어떻게 수정하면 좋을까요?

2024-01-08 05:59 UTC, sujin0707 commented on package.json
> +    "jest": "^29.7.0",
아마 터미널에 npm run test를 해보기 위해서는 jest를 설치해야 해서 추가했던 것으로 기억합니다.
cypress는 브라우저에서 로컬 서버를 띄우지 않은 상태에서도 크롬 개발자 도구를 보면서 개발이 가능하다는 특징이 있습니다. (브라우저에서 watch & hot reload 사용)
이와 반면에 jest는 터미널에서 watch & hot reload를 사용합니다.

2024-01-08 05:59 UTC, sujin0707 commented on src/Card.js
> +  }g
수정 후 다시 commit하겠습니다!

2024-01-09 14:00 UTC, sujin0707 commented on src/Card.js
> +    this.element.addEventListener('click', this.handleCardClick.bind(this));
1. 두 데이터 혹은 정보의 소스를 일치시키는 기법을 의미합니다. 즉, 화면에 보이는 데이터와 브라우저 메모리에 있는 데이터(여러개의 JavaScript 객체)를 일치시키는 것을 말합니다.
2. 이벤트를 받아 줄 요소를 선택한 후, 선택한 요소가 어떤 이벤트에 반응할지, 즉 요소와 이벤트를 연결해주는 역할을 수행하기 위해서는 바인딩이 필요하기 때문입니다.
3. const obj = {
	name: 'car',
        getname () {
    	    return this.name;
    },
};

console.log(obj.getname()); ->car
위와 같이 this가 점 바로 앞에 있는 객체에 매핑되는 것을 암시적 바인딩이라고 하며, 명시적 바인딩 외에도 이와 같은 암시적 바인딩과 같은 방식도 존재합니다.

2024-01-09 16:12 UTC, sujin0707 commented on index.css
> +  font-size: 16px;
감사합니다!

2024-01-09 16:12 UTC, sujin0707 commented on src/index.js
> +class CardGame {
분리 후 push 했습니다

2024-01-09 16:12 UTC, sujin0707 commented on src/Card.js
> +    alert(this.isWinner ? '당첨입니다' : '꽝입니다');
최대한 수정해서 push 했으나 오류가 생기는 거로 보아 아직 미흡한 것 같습니다 ㅠㅠ

2024-01-09 16:12 UTC, sujin0707 commented on src/index.js
> +cardGame.start();
수정해서 push 했습니다!

2024-01-09 16:14 UTC, sujin0707 commented on src/index.js
> +cardGame.start();
클릭 시 handleCardClick 메서드가 실행되도록 하는 방식으로 수정했습니다

2024-01-09 16:28 UTC, tkdrb12 requested changes

2024-01-09 16:28 UTC, tkdrb12 commented on src/Card.js
> +  }
```suggestion
  handleCardClick() {
    const resultMessage = document.createElement('p');
    resultMessage.textContent = this.isWinner ? '당첨입니다' : '꽝입니다';

    const resultContainer = document.querySelector('#result');
    if (!resultContainer.hasChildNodes()) {
      resultContainer.appendChild(resultMessage);
    }
  }
  
```


바인딩한 함수를 호출시에 인자를 전달하지 않아 오류가 발생했습니다.
해당 개념이 어려우다면 call, apply, bind함수의 차이점을 찾아보다보면 좀 더 이해를 쉽게 하실 수 있을 것 같아요!

2024-01-09 16:45 UTC, sujin0707 commented on src/Card.js
> +  }
피드백 감사합니다!

2024-01-09 16:46 UTC, tkdrb12 approved these changes

2024-01-09 16:47 UTC, merged